theme: jekyll-theme-minimal
title: David Tabaka
description: Senior Front-End Developer and People Manager
logo: logo.jpg

sidebar:
  - name: Lviv, Ukraine
  - name: GitHub
    link: github.com/dabakovich
  - name: dabakovich@gmail.com
    link: mailto:dabakovich@gmail.com
